SCRIPT_PACKAGE_TYPE_STRING = 0
SCRIPT_PACKAGE_TYPE_STRING0 = 1
SCRIPT_PACKAGE_TYPE_BIGSTRING = 2


BIGSTRING_ENABLE = 1
SCRIPT_PACKAGE_TYPE = SCRIPT_PACKAGE_TYPE_BIGSTRING
SERVICE_ID_ENABLE = 1
SERIAL_NUM_LEN = 2
